version: '3'

services:
  development.api:
    build: .
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=development
  staging.api:
    build: .
    ports:
      - "5000:80"
    environment: 
      - ASPNETCORE_ENVIRONMENT=staging
  